engines:
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      extensions:
      - .js
      - .jsx

ratings:
   paths:
   - "**.js"
   - "**.jsx"

exclude_paths:
- node_modules/**/*
- "**/test/"
