environment:
  nodejs_version: "6"

  install:
    - ps: Install-Product node $env:nodejs_version
    - npm install

  build:
    - node --version
    - npm --version
    - npm run build

  test_script:
    - npm run coverage