environment:
  nodejs_version: "12"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - npm --version
  - yarn --version
  - yarn link:packages
  - yarn build
  - yarn coverage

build: off