environment:
  nodejs_version: "10"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - node --version
  - npm --version
  - yarn --version
  - npm run link:packages
  - npm run build
  - npm run coverage

build: off